### ISSUE TITLE
Clarification on "No Derivatives"

### ISSUE THREAD

**Issue by firasm** [clauswilke/dataviz#100]
Hi Claus,

Hope you're doing well - thanks for putting together this fantastic book! I intend to use it as a reference in a Data Visualization course I am teaching this term at UBC ([DSCI 531](https://ubc-mds.github.io/descriptions/).

I just wanted to quickly clarify the "No derivatives" portion of your CC4 license. According to my understanding ([ref](https://mollykleinman.com/2008/10/20/cc-howto-no-derivatives/), ND implies that if I make any modifications (including alter, transform, build upon) I am no longer able to "redistribute them" without permission from the original author. The problem is that all materials from the DSCI 531 course I teach has traditionally been licensed as "CC BY-SA 4.0".

I intend to use some of the examples from your book as clicker and worksheet questions for students to work on in class and labs. This will require some altering and transforming as at the very least I would like to remove the annotations of "bad" and "ugly" if for instance, I show them a plot and ask them if it is an effective visualization. 

I guess my work-around could be that I simply hide those slides when I share my lecture materials, but I thought I'd ask for permission just in case you were so inclined.

By the way, for material such as this, I totally understand the need to apply a ND - there are too many potential issues that could arise from transformations and then subsequent attributions to you or the book. 

Let me know what you think!

Cheers,

Firas

**Comment by clauswilke** [comment]
There isn't much I can say. Licensing is handled by O'Reilly, and the ND license was chosen by them. You could reach out to their legal department and ask if they can provide guidance for your specific use case.

I'm going to close the issue, but if you have any further comments or information feel free to post here.
