### ISSUE TITLE
Naming of "Sina plots" might be contentious

### ISSUE THREAD

**Issue by tjebo** [clauswilke/dataviz#111]
Claus
First of all, thanks so much for this incredible book. 

The issue below is not really an issue, and is certainly also a matter of taste, but I would like to point it out just in case it slipped the author's attention. 

I am not sure if might not be contentious to call Sina plots ... Sina plots. 

For example, the ggbeeswarm package is using this visualisation since at least 2016 (as per last commit to https://github.com/eclarke/ggbeeswarm/blob/master/R/geom-quasirandom.R). 

This is using the vipor package (https://cran.rstudio.com/web/packages/vipor/index.html), which seems dedicated to this visualisation since a long time before submission of the paper by Sidiropolous et al. 

And this is only what I am aware of, I am sure there must be others who have used this type of visualisation before. 
Again, I understand it is a matter of taste, and naming things after people is usually not exactly "fair". Just wanted to point this out. 

Best wishes
Tjebo

**Comment by clauswilke** [comment]
Thanks for pointing to these packages. I'd argue that for the name to be contentious, there needs to be a different name that people also use or argue should be used. I don't see that that's the case. There's the name "beeswarm", but to me a beeswarm plot is different from a sina plot. It's what `geom_beeswarm()` produces, and it has clear structure to the arrangement of the points.

The vipor package calls these plots "violin scatterplot". I don't think this name has caught on. I also don't think it's quite right. If we wanted to name the plot according to what it is, something like "violin stripchart" would seem more appropriate to me. But I don't think anybody uses that term.
