### ISSUE TITLE
Use of color and legend order in some Titanic figures (Chapter 5)

### ISSUE THREAD

**Issue by mikelmadina** [clauswilke/dataviz#12]
Thanks for sharing your work at this early stage, looking forward to get (and recommend!) the final book.

Two details to improve the overall coherence of figures using the Titanic dataset in chapter 5:

Figure 5.9, which is OK by itself, shows females distribution in blue, while all the other figures using this dataset use blue for males.

Also, you could consider to rearrange the order of genders in the legend in figure 5.6 to match the ones in 5.7 and 5.8; or, as I assume that the reordering is due to the same reasons explained later in figures 14.5 and 14.6, it would suffice to add a reference to that explanation.

**Comment by clauswilke** [comment]
Thanks for pointing this out. It's an oversight. The colors were meant to be the same throughout that chapter.
