### ISSUE TITLE
Typo in Preface

### ISSUE THREAD

**Issue by espinielli** [clauswilke/dataviz#13]
In "Good, bad, and ugly figures" there is a missing "to" 
FROM: 
Throughout this book, I show many different versions of the same figures, some as examples of how make a good visualization and some as examples of how not to.

TO:
Throughout this book, I show many different versions of the same figures, some as examples of how to make a good visualization and some as examples of how not to.

I.e. from "...how make a good visualization..." to "...how to make a good visualization..."

**Comment by clauswilke** [comment]
Thanks, closed on github.
