### ISSUE TITLE
Feature request: direct links to code

### ISSUE THREAD

**Issue by sjspielman** [clauswilke/dataviz#16]
Hi Claus, 

It would be a really good addition, I think, to see if either it's possible to make figures into links in Rmarkdown, or similarly have footnotes or captions throughout the book, directly linking each fig to its source code. That way, people reading the online version can immediately jump to the code they need to reproduce.

-Stephanie

**Comment by clauswilke** [comment]
This won't happen. I'll have to write a frequently asked questions section somewhere to address this request. Leaving the issue open for that reason. (The only way this could happen is if rmarkdown added the feature natively. This is a request for the maintainer of rmarkdown.)

**Comment by clauswilke** [comment]
FAQ added to README: https://github.com/clauswilke/dataviz/blob/master/README.md
