### ISSUE TITLE
Section 2.2 Log Scale Explanation

### ISSUE THREAD

**Issue by WillKoehrsen** [clauswilke/dataviz#19]
The text above Figure 2.4 reads:

$100^{0.5} \approx 31.6$

However

$100^{0.5} = 10$

**Comment by clauswilke** [comment]
You're correct, thanks. It should be $10^{1.5}$ instead of $100^{0.5}$. I'll fix it.

**Comment by WillKoehrsen** [comment]
Thanks, and thank you for writing a great book! Sorry for having to raise an issue over such a minor point.

**Comment by clauswilke** [comment]
On the contrary, thanks a lot for pointing this out. It's very helpful to receive these comments. Please open an issue for anything else you may see, even if it's just a typo.
