### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by clairemcwhite** [clauswilke/dataviz#2]
Since you asked

Section 1: First sentence parallel structure, 'convert' -> 'converting'

Section 1.2: 'tempterature'

Section 6.2: 'useles'

Section 6.3: 'acutal' 

Section 7.1: 'wisker' -> 'whisker'

Section 14.2: 'lifes'

**Comment by clauswilke** [comment]
I think the first one is correct. All others have been fixed on github.
