### ISSUE TITLE
9.2 The case for side-by-side bar charts (and maybe line plots?)

### ISSUE THREAD

**Issue by ngiangre** [clauswilke/dataviz#28]
This is a great read through, thank you so much for your hard work and great communication!

I was reading through chapter 9, section 9.2 and I totally agree the side-by-side bar chart is the most logical choice in comparison to stacked bar charts and pie charts. I don't know if you cover this later, but I was thinking to myself I would have actually done a line plot where each line is a company, the x axis is the year, and the y axis is the share percent. My only grievance with this kind of plot is that the overlapping lines could obfuscate trends whereas the side-by-side bar chart doesn't have that problem. However, it is a bit tougher to see yearly trends of of the companies just by tracing the height of a bar across each group (but that's minor). I was hoping to hear what you think of the use of a line plot in this case? Thanks!

**Comment by clauswilke** [comment]
Line plots are covered in Chapter 13, using somewhat different examples (e.g., [Figure 13.8](https://serialmentor.com/dataviz/time-series.html#fig:oats-yield)).
