### ISSUE TITLE
Typo @ 21.2p2

### ISSUE THREAD

**Issue by cschu** [clauswilke/dataviz#33]
A general, the program **mangers** told me, should be able to look at each figure and immediately see how what we were doing was improving upon or exceeding prior capabilities.

This should probably be managers or is it intentional...?

**Comment by clauswilke** [comment]
Thanks. Fixed on github.

**Comment by cschu** [comment]
Got another one: weekedays in Figure caption 21.6. For future reference, should I just add on here or should I open a new issue for each typo?
