### ISSUE TITLE
Section about continuous color scales/colormaps

### ISSUE THREAD

**Issue by apcamargo** [clauswilke/dataviz#37]
I think the book would benefit greatly with a section describing the importance of using perceptually-uniform colormaps.

This is a good resource about this matter: https://bids.github.io/colormap/

**Comment by clauswilke** [comment]
Could you clarify what exactly you think is missing in the existing chapters on color use, and in particular this one:
https://serialmentor.com/dataviz/color-pitfalls.html#using-non-monotonic-color-scales-to-encode-data-values

Thanks!

**Comment by apcamargo** [comment]
I missed the "Using non-monotonic color scales to encode data values" section. I'm sorry.

Thank you, Claus!
