### ISSUE TITLE
Small typo in chapter 1

### ISSUE THREAD

**Issue by AndrewKinsman** [clauswilke/dataviz#4]
Hi Claus,

I discovered your book today via social media and I am very much enjoying it (and learning a bunch of stuff along the way!), thank you. 

FYI, in chapter 1 there is a small typo:
"Let’s put things into practice. We can take the dataset shown in Table 1.2, map tempterature onto the y axis," 
Obviously it should be "temperature".

Best regards,
Andrew

**Comment by clauswilke** [comment]
Thanks, fixed.
