### ISSUE TITLE
Section about visualization of intersecting sets

### ISSUE THREAD

**Issue by apcamargo** [clauswilke/dataviz#42]
Currently, the book doesn't have a section dedicated to the representation of multiple intersecting sets. This subject may be within the scope of the book and it's inclusion should be interesting.

I would suggest a discussion about Venn diagrams and [UpSet plots](https://cran.r-project.org/web/packages/UpSetR/README.html).

**Comment by clauswilke** [comment]
I agree this is an interesting topic, but it's simply not going to make the cut. Maybe in a future 2nd edition.
