### ISSUE TITLE
Discrepancy in the Okabe and Ito palette

### ISSUE THREAD

**Issue by apcamargo** [clauswilke/dataviz#44]
[In the book](https://serialmentor.com/dataviz/color-pitfalls.html#not-designing-for-color-vision-deficiency), `#999999` is listed as a color of the Okabe and Ito (2008) palette. But this color is not listed in [their site](http://jfly.iam.u-tokyo.ac.jp/color/), they use `#000000` instead.

Is there a reason to use `#999999` in the book? As a deutan, I find `#000000` much easier to see, as it contrasts better with the other colors of the palette.

Thank you for all the work you put on this book!

**Comment by clauswilke** [comment]
I'm pretty certain I took it from their site. Maybe they changed their recommendation without flagging an update?

See also here: https://github.com/clauswilke/colorblindr/blob/master/R/palettes.R

**Comment by apcamargo** [comment]
It could be! Anyway, I'd propose to at least mention this variation in the book. I've asked to other colorblind colleges and they all find that the black is easier to distinguish because of the lightness contrast.

**Comment by clauswilke** [comment]
I've changed this in the .Rmd file. Will go live when I rebuild the website the next time.

**Comment by apcamargo** [comment]
Figure 4.1 is still showing the gray tone.

https://serialmentor.com/dataviz/color-basics.html

**Comment by clauswilke** [comment]
I don't see it.
<img width="840" alt="screen shot 2018-09-27 at 8 33 53 am" src="https://user-images.githubusercontent.com/4210929/46149531-26349880-c230-11e8-8a86-2bbf8d0eab9d.png">

**Comment by apcamargo** [comment]
I'm really sorry. I got confused with the colors and though the pink (`#cc79a7`) in figure 4.1 was the gray (`#999999`).
