### ISSUE TITLE
Suggestion for 1:1 ratio line in daily temperature normals plots

### ISSUE THREAD

**Issue by ahuang11** [clauswilke/dataviz#45]
I think it would be beneficial to add a translucent, perhaps dotted, 1:1 ratio line which can highlight that Houston is generally warmer than San Diego most of the time.

![image](https://user-images.githubusercontent.com/15331990/44941491-49fcdf80-ad53-11e8-9c73-dd97cdc0f134.png)

(Please excuse this poor edit done in Paint)

**Comment by clauswilke** [comment]
That's not an important point of the figure in the context where it appears. It would simply make the figure busier and more complicated to explain.
