### ISSUE TITLE
Add subsection about memorable figure.

### ISSUE THREAD

**Issue by clauswilke** [clauswilke/dataviz#48]
In the "telling a story" figure, it might make sense to add a brief section called "Make a memorable figure". Research has shown that embellished figures can be more memorable than plain figures (e.g.: 
[Bateman et al. 2010](http://hci.usask.ca/uploads/173-pap0297-bateman.pdf)). I just need a good idea for an embellished figure.

**Comment by steveharoz** [comment]
Some of the Otto Neurath graphs may make for useful examples. E.g. [this one](https://78.media.tumblr.com/5fde3c1f27f781c98a3d47903d477677/tumblr_nhzdbrau411rpgpe2o5_1280.jpg)

I've never found a reasonably simple way to implement them with ggplot, but you might have a better understanding of R's graphics.

**Comment by clauswilke** [comment]
I've been thinking along those lines today, e.g. visualizing the `msleep` dataset using the animal silhouettes available here: http://phylopic.org/ 

Just not sure how much effort I want to put towards writing a geom that can do this. It's likely at least a week of work.

**Comment by clauswilke** [comment]
To implement this, we'd have to take `geom_col()` and replace the drawing subroutine with a function that covers the area of each bar with tiles of images. I see no technical hurdle to doing this. Just requires a bit of calculation to get this right without distorting the aspect ratio of the images and to make it responsive if the image is resized.

**Comment by clauswilke** [comment]
I think I'll just write a grob that can tile an arbitrary rectangular area with an image. This will also address the longstanding request of being able to draw bars with textured fill. https://stackoverflow.com/questions/2895319/how-to-add-texture-to-fill-colors-in-ggplot2

**Comment by clauswilke** [comment]
Something like this is going to do the job. The rest is just filling in the blanks and adding a nice API.

``` r
library(grid)
library(magick)
#> Linking to ImageMagick 6.9.9.39
#> Enabled features: cairo, fontconfig, freetype, lcms, pango, rsvg, webp
#> Disabled features: fftw, ghostscript, x11

get_asp <- function(img) {
  info <- image_info(img)
  info$height / info$width
}

texture_grob <- function(x = unit(0.5, "npc"), y = unit(0.5, "npc"),
                         width = unit(1, "npc"), height = unit(1, "npc"),
                         img = NULL) {
  vp <- viewport(x, y, width, height, just = c(0, 0), clip = "on")
  g <- gTree(img = img, cl = "texture_grob", vp = vp)
}

makeContent.texture_grob <- function(x) {
  grob_width <- convertWidth(unit(1, "npc"), "in", valueOnly = TRUE)
  grob_height <- convertHeight(unit(1, "npc"), "in", valueOnly = TRUE)
  grob_asp <- grob_height / grob_width
  asp <- get_asp(x$img)
  n <- ceiling(grob_asp/asp) # number of image copies we need
  
  bg <- rectGrob(gp = gpar(fill = "#E8E8E8"))
  children <- lapply(
    1:n,
    function(i) {
      vp = viewport(
        x = unit(0, "in"), y = unit(i*asp*grob_width, "in"),
        width = unit(grob_width, "in"), height = unit(asp*grob_width, "in"),
        just = c(0, 1)
      )
      rasterGrob(x$img, vp = vp)
    }
  )
  # add background to children
  children <- c(list(bg), children)
  
  # convert to gList and set
  children <- do.call(gList, children)
  setChildren(x, children)
}

img <- magick::image_read("https://jeroen.github.io/images/Rlogo.png")

grid.newpage()
tg1 <- texture_grob(unit(.2, "npc"), unit(.05, "npc"), unit(.1, "npc"), unit(.9, "npc"), img)
tg2 <- texture_grob(unit(.5, "npc"), unit(.05, "npc"), unit(.3, "npc"), unit(.6, "npc"), img)
grid.draw(tg1)
grid.draw(tg2)
```

![](https://i.imgur.com/DP1i8SG.png)

Created on 2018-09-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
I think dependency on the plot aspect ratio is unavoidable. Similar issues arise with other packages, e.g. ggrepel. The label location changes every time you change the plot size.

For the problem of different tiling images with different aspect ratios, my perspective is that the underlying drawing infrastructure should do general-purpose tiling. Then, any desired effect can be obtained with that infrastructure by providing appropriately formatted and/or padded images. The padding could even be done in R with the magick package.

**Comment by steveharoz** [comment]
Do you know how to get the plot aspect ratio? Is there a `get_panel_size_in_pixels()` function in grid? If so, you could compensate for the image aspect ratio. The reason why I bring it up is that in most unit charts, a unit has a specific scale, like 1 elephant icon = 10,000 elephants. If the number of items changed with aspect ratio, it could become misleading.

**Comment by clauswilke** [comment]
I think the right way to solve this problem is to make it possible to use the tiling images at a specified height or width and then ideally tie that to the scale in ggplot, so that e.g. one image height corresponds to x units on the scale regardless of the plot size or aspect ratio. I think that's possible, but I won't be able to look into this further until later this fall.

**Comment by clauswilke** [comment]
I've got it figured out: https://github.com/clauswilke/ggtextures
(Legends aren't implemented yet.)

``` r
library(ggplot2)
library(tibble)
library(ggtextures)

data <- tibble(
  count = c(5, 3, 6),
  animal = c("giraffe", "elephant", "horse"),
  image = list(
    "http://steveharoz.com/research/isotype/icons/giraffe.svg",
    "http://steveharoz.com/research/isotype/icons/elephant.svg",
    "http://steveharoz.com/research/isotype/icons/horse.svg"
  )
)

ggplot(data, aes(animal, count, image = image)) +
  geom_isotype_col() +
  theme_minimal()
```

![](https://i.imgur.com/wTi6wTc.png)

``` r

ggplot(data, aes(animal, count, image = image)) +
  geom_isotype_col(
    img_width = grid::unit(1, "native"), img_height = NULL,
    ncol = NA, nrow = 1,
    hjust = 0, vjust = 0.5
  ) +
  coord_flip() +
  theme_minimal()
```

![](https://i.imgur.com/FA2y8MS.png)

Created on 2018-09-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
