### ISSUE TITLE
include the figure cited from The Economist 2011

### ISSUE THREAD

**Issue by espinielli** [clauswilke/dataviz#59]
In section 1 of chapter 19, "Figure titles and captions", the dataviz ["Corrosive corruption" from The Economist](https://www.economist.com/graphic-detail/2011/12/02/corrosive-corruption) is cited and a point is made for deviations from its design in figure 19.1.
IMHO not having the original available is a problem because it does not allow for a quick and easy comparison with the proposed changes.
It could maybe worth asking permission to The Economist to include the figure in the book...(the worst you can get is a no ;-)

**Comment by clauswilke** [comment]
I don't plan to include the original figure from the Economist, but I think that the text flow will be improved by swapping the first and the second figure in that chapter. Adding this to my todo list.

**Comment by clauswilke** [comment]
Thanks again for your comment. I have revised the chapter text without changing the figures. I think the key is to not create an expectation in the reader that they must see the original economist figure.
