### ISSUE TITLE
Principles of figure design - choosing a font

### ISSUE THREAD

**Issue by ShanEllis** [clauswilke/dataviz#6]
First, piggybacking off of what Jeff said, I'm so very excited for this book. It looks awesome so far! 

Realizing it's a work in progress, I was wondering if you had considered explaining how to change/control font on graphs in R/ggplot2. I use the 'extrafont' package to do this, but I would surely be willing to change my approach.  This may be outside the scope of the book and apologies if I've missed it in your plan, but figured I'd mention it!

**Comment by clauswilke** [comment]
Thanks for your feedback. This particular book will not provide any specific programming advice. I don’t want to limit my audience by turning it into a book for R users only (or even primarily).
