### ISSUE TITLE
The need to see thought process

### ISSUE THREAD

**Issue by GuiMarthe** [clauswilke/dataviz#7]
What an awesome book Claus!

I just want to take this opportunity to suggest something a few things that I believe might add to the book.

See, with subjects like these, I think two things are of great value:

### 1. Thought process explanation

I think that in the end, you could add a few visualizations where you explain the thought process into why that is a good choice (subjectively, of course) and what would be the wrong and alternative ways you could have constructed the visualization at hand.

A book that I think really nails this aspect (though not for data vis, but for statistical modelling) is [Regression Modeling Strategies](http://www.springer.com/gb/book/9781441929181) in which he explains quite nicely decisions that he took for modelling phenomena and what could've been some right choices and what would be some wrong ones. Even though data viz can be some what more subjective, I think you could emphasize that aspect and still provide value for people with this idea.

### 2. Some advice on reporting it self

I think that not enough time is spent on how reports should be developed around data visualizations.  
Some principles and examples could help orchestrate a set of many visualizations. I'm thinking on how to coordinate fonts, colors, when to deviate from a chosen color scheme, how to mix different viz on the same type of data (ie. many visualizations of proportions) in a report. How to title and annotate viz coherently, throughout a report. 

So those are a few two cents :smile: 

Congrats on the great book!

**Comment by clauswilke** [comment]
Thanks for your comments. For point 2, I think planned Chapter 29 (in the Outline) will cover this to some extent. For point 1, my goal was to address this throughout, by giving good/bad examples, explaining why they are good/bad, etc. If you feel the current draft is missing an important component of thought process, it would be helpful if you could provide a concrete example.

**Comment by clauswilke** [comment]
Closing this, because it's unclear whether it still applies to current draft.
