### ISSUE TITLE
Refine diagram to avoid potential mis-interpreting labels

### ISSUE THREAD

**Issue by tillnagel** [clauswilke/dataviz#81]
In the [density plots showing ages of Titanic passengers](https://serialmentor.com/dataviz/histograms-density-plots.html#fig:titanic-age-fractional-dens), the two labels "male .. " and "female passengers" are centered but seem closest to the gray area showing total, and thus might be interpreted on a quick glance as labelling that area.

Maybe one of these variations might make it clearer.
![dataviz-fig7-9](https://user-images.githubusercontent.com/908847/50378234-79e73000-062d-11e9-85ef-4122eba9f63d.png)

**Comment by clauswilke** [comment]
Thanks for your feedback. I've thought it over and decided to leave things as they are. That doesn't mean I disagree with you; it's just a matter of cost-benefit of revising figures this late in the production process.
