### ISSUE TITLE
Discussion of Figure 15.5

### ISSUE THREAD

**Issue by cmwerner** [clauswilke/dataviz#84]
The sentence "First, Alaska seems weirdly stretched out compared to how it looks, for example, in Figures 15.2 or 15.4" seems strange given it follows the discussion of how the Mercator projection stretches areas near the poles (Figure 15.2). It's stretched in a different way, but it might be better to compare to 15.3 or only 15.4?

**Comment by clauswilke** [comment]
The Mercator projection is shape preserving, so Alaska looks (almost) right in Figure 15.2, it's just shown with the wrong size.
