### ISSUE TITLE
Chapter 4 typ0

### ISSUE THREAD

**Issue by EconProf** [clauswilke/dataviz#87]
Figure 4.7: Example accent color scales, each with four base colors and three accent colors. Accent color scales can be derived in several different ways: (top) we can take an existing color scale (e.g., the Okabe Ito scale, Fig 4.1) and lighten and/or partially desaturate some colors while darkening others; (middle) we can take gray values and pair them with colors; (bottom) we can take work with an existing accent color scale, e.g. the one from the ColorBrewer project.

delete the "take" from the bottom option?

**Comment by clauswilke** [comment]
Thanks, fixed in my files.
