### ISSUE TITLE
Overlapping dots in dotplot

### ISSUE THREAD

**Issue by nielsswinkels** [clauswilke/dataviz#88]
Not sure if this is a bug, and not sure where to fix it, so I'm posting it as an issue instead:

In this image, the dots of the dotplot slightly overlap on some places. My guess is that that is not supposed to happen?
https://serialmentor.com/dataviz/visualizing_uncertainty_files/figure-html/election-quantile-dot-1.png

From chapter 16.1: https://serialmentor.com/dataviz/visualizing-uncertainty.html

**Comment by clauswilke** [comment]
It's a property of quantile dotplots that can't always be avoided. It depends on how well a distribution can be represented by equally sized circles. I have reviewed the figure and have decided to leave it as is.
