### ISSUE TITLE
Mistake in ecdf hypothetical class example

### ISSUE THREAD

**Issue by hajduakos** [clauswilke/dataviz#89]
I believe that there is a small mistake in the first example in Section 8.1.

> We can plot the total number of students that have received **at least** a certain number of points versus all possible point scores.

Shouldn't this be **at most** a certain number of points? Because then you say

> This plot will be an ascending function, starting at 0 for 0 points and ending at 50 for 100 points.

which would mean that 0 students received at least 0 points and 50 students received at least 100 points, which is obviously not true.

**Comment by clauswilke** [comment]
Yes, you are correct, thanks! This will be fixed in the printed book.
