### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Xavier-Wang-19** [clauswilke/dataviz#90]
29.1
> I will argue that late 2013 marks the point in time when preprints took off in biology, and ironically this caused the q-bio archive to slow its growth. ... In fact, soon after its launch, bioRxiv started experiencing rapid, exponential growth in monthly submissions, and the slowdown in q-bio submissions exactly **conincides** with the start of this exponential growth in bioRxiv (Figure 29.2).

"conincides" may be "coincides".

**Comment by Xavier-Wang-19** [comment]
29.2
> Some might hear this story and conclude that the generals are not very smart or just not that into science. I think that’s exactly the wrong take-home message. The generals are simply very busy. They can’t spend 30 minutes trying to **decypher** a cryptic figure.

"decypher" may be "decipher".

**Comment by Xavier-Wang-19** [comment]
29.2
> Figure 29.3: Mean arrival delay versus distance from New York City. ... Delta has **consistenly** lower arrival delays than other airlines, regardless of distance traveled.

"consistenly" may be "consistently".

**Comment by Xavier-Wang-19** [comment]
29.3

> Sometimes, however, we do want to show more complex figures that contain a large amount of information at once. ... Never jump straight to a highly complex figure; first show an easily **digestable** subset.

"digestable" may be "digestible".

**Comment by clauswilke** [comment]
Thanks!

**Comment by mariemoinet** [comment]
Another one on the legend of figure 9.1 : "because because"
