### ISSUE TITLE
Using shape for continuous values

### ISSUE THREAD

**Issue by tjochmann** [clauswilke/dataviz#91]
In 2.1 you state, that "shape [...] can only represent discrete data.". I do not fully agree to that statement. An aesthetics commonly used for the visualization of tensor fields are ellipses and ellipsoids with continouously altered shape (size, orientation and ratio of the principial axes). For example, see https://www.researchgate.net/publication/225828730_A_Riemannian_Scalar_Measure_for_Diffusion_Tensor_Images or https://www.researchgate.net/publication/225228439_Riemannian_Anisotropic_Diffusion_for_Tensor_Valued_Images.
Your book is a joy to read. Thank you very much!

**Comment by clauswilke** [comment]
Thanks. I have added the qualifying word "usually". At this point in the book, I don't want to go into the details of how shapes could be made to represent continuous values.
