### ISSUE TITLE
Chapter 7 - Histograms

### ISSUE THREAD

**Issue by stephenkey3** [clauswilke/dataviz#94]
In section 7.1 of chapter 7, you discuss creating a histogram "by drawing filled rectangles whose heights correspond to the counts and whose widths correspond to the width of the age bins." You should explain that this is only valid if the width of the bins are all the same. If, for example, I combined the 26-30 and 31-35 bins into a single bin, the chart would have a very tall and wide column and would not be a histogram.

**Comment by clauswilke** [comment]
Thanks, I agree, and I think I can still get this fixed for the print version. Will submit a fix to the free online version within the next few days.
