### ISSUE TITLE
Statistical significance language

### ISSUE THREAD

**Issue by NiclasRudolfson** [clauswilke/dataviz#96]
Small issue in chapter 16:
> For bars from Switzerland, the 95% confidence interval on the difference just barely includes the value zero. Thus, there is a slightly bigger than 5% chance that the observed difference between mean ratings of U.S. and Swiss chocolate bars represents nothing more than sampling variation

this seems to be technically incorrect, and implies that CIs or p-values can be interpreted as probabilities of hypotheses

**Comment by clauswilke** [comment]
I guess you're right. The book is off to the printer, so it's not something I can fix anymore for this edition.

**Comment by NiclasRudolfson** [comment]
Ah, too bad. Absolutely loving the book btw, recommending it to all my colleagues!

**Comment by clauswilke** [comment]
The book is now in print, and errata can be submitted here: https://www.oreilly.com/catalog/errata.csp?isbn=0636920137733

**Comment by clauswilke** [comment]
I submitted an erratum, and this should be fixed in the next printing of the book.
